apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: coit-frontend
  labels:
    app: coit-frontend
    runon: fargate
spec:
  selector:
    matchLabels:
      app: coit-frontend
  replicas: 3                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        runon: fargate
        app: coit-frontend                                  # 6
        app.kubernetes.io/name: coit-frontend
    spec:
      volumes:
        - name: myappconfig
          configMap: 
            name: coit-frontend
      containers:
        - image: basilvarghese/myapp-frontend:latest
          imagePullPolicy: IfNotPresent                         # 7
          name: coit-frontend
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_NAME
              value: mydb
          volumeMounts:
            - name:  myappconfig
              mountPath: "/mnt"