# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
   sudo apt-get update
   sudo apt-get install -y npm
  displayName: 'Installing npm using apt-get'

- script: |
   npm audit || true
  displayName: 'check for vulnaribities'

- script: |
   npm test || true
  displayName: 'perform unit test'

- script: |
   sonar-scanner ./ || true
  displayName: 'review code'

- script: |
   npm install
   npm run build
  displayName: 'npm install and build'

- script: |
   sudo apt-get install wget apt-transport-https gnupg lsb-release
   wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
   echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
   sudo apt-get update
   sudo apt-get install trivy
  displayName: 'Installing trivy'

- script: |
   trivy config Dockerfile
  displayName: 'Scan the Dockerile for Security'

- script: |
   BASE_IMAGE=`grep FROM Dockerfile | awk '{print $2}'`
   trivy image $BASE_IMAGE
  displayName: 'scanning the base image'

- script: |
   trivy config K8s
  displayName: 'scanning the manisfest files'

- script: |
   sudo docker build -t incharagowda/frontend-project:1.0.1 . 
  displayName: 'Build the container image'

- script: |
   echo $(DOCKER_HUB_PASSWORD) | sudo docker login --username=$(DOCKER_HUB_USERNAME) --password-stdin
   sudo docker push incharagowda/frontend-project:1.0.1
  displayName: 'Login to registry and Push the image'
  