# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    docker build -t ajayjohn100/frontend-project:latest . -f Dockerfile
  displayName: 'Build conainer image'

- script: |
    docker run -d ajayjohn100/frontend-project:latest . -f Dockerfile
  displayName: 'check the application is running or not'

- task: Docker@2
  displayName: push to docker
  inputs:
    command: push
    containerRegistry: azure
    repository: ajayjohn100/frontend-project
    tags: latest


  
