apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../resources

images:
- name: basilvarghese/myapp-frontend
  newTag: 1.0.0

namespace: stage

replicas:
- name: coit-frontend
  count: 4

namePrefix: customer1-
nameSuffix: -stage
